### ISSUE TITLE
few issues with current implementation 

### ISSUE THREAD

**Issue by keighrim** [clamsproject/app-fewshotclassifier#6]
I was working on updating the app in `dev` branch to the latest SDK, and found some issues. 

* [x] model version specification should appear somewhere in the metadata. (https://github.com/clamsproject/app-fewshotclassifier/compare/6a6380af01ab...06afca47df06#diff-f5f717dd8c4c0d49270a68d5764bce65a22e051a1deee6bbfcc2d9bce3e0c6b1R31-R34)
* [x] `config.py` can be mostly merged into configurable params into `metadata.py`, and for the non-configurables, we can just use python module constant in the `app.py`
* [x] many lines in the app code can now be replaced with `video_doc_helper` and `self.logger`.
* [ ] we need a better way to feed the app with a new index csv file when the app is running as a container. Both in code and documentation.

**Comment by snewman-aa** [comment]
Took care of 1-2 with [this commit](https://github.com/clamsproject/app-fewshotclassifier/commit/7799ed8528066db42328fdb550aefae162645bab) 

Took care of item 3 in main branch last week
